#!/usr/bin/env python
"""Apply quarantine decision JSON files generated by Cursor/Codex triage."""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path
from typing import Any, Optional, Tuple

import autosortd_1py as m


def _parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=r"C:\\_AUTOSORT")
    ap.add_argument("--dry-run", action="store_true")
    return ap.parse_args()


def _iter_decision_files(quarantine_dir: Path):
    if not quarantine_dir.exists():
        return []
    return sorted(quarantine_dir.glob("*.decision.json"))


def _load_payload(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, dict):
        raise ValueError("decision.json must be a JSON object")
    return data


def _candidate_source_path(
    quarantine_dir: Path,
    decision_file: Path,
    payload: dict[str, Any],
) -> Tuple[Optional[Path], str]:
    for key in ("file_path", "source_path", "path", "src", "original_path"):
        raw = payload.get(key)
        if isinstance(raw, str) and raw.strip():
            candidate = Path(raw.strip())
            if candidate.exists():
                return candidate, key
            rel = decision_file.parent / raw.strip()
            if rel.exists():
                return rel, f"{key}(relative)"

    # fallback by name from <base>.decision.json => <base>
    base_name = decision_file.name[: -len(".decision.json")]
    direct = quarantine_dir / base_name
    if direct.exists():
        return direct, "name"

    # some emitters may include extension in decision filename
    if base_name:
        for name in (".pdf", ".docx", ".xlsx", ".xls", ".ppt", ".pptx", ".doc"):
            if base_name.endswith(name):
                alt = quarantine_dir / base_name
                if alt.exists():
                    return alt, "name(ext)"
    return None, "missing"


def apply_decisions(root: Path, dry_run: bool) -> int:
    rules_cfg = m.load_yaml(root / "rules" / "rules.yaml")
    mapping_cfg = m.load_yaml(root / "rules" / "mapping.yaml")
    if not rules_cfg or not mapping_cfg:
        print("error: failed to load rules/mapping from", root / "rules", file=sys.stderr)
        return 1

    paths = m.Paths(
        root=root,
        staging=root / "staging",
        out=root / "out",
        quarantine=root / "quarantine",
        dup=root / "dup",
        logs=root / "logs",
        cache=root / "cache",
        rules_dir=root / "rules",
    )
    m.ensure_dirs(paths)

    decisions = _iter_decision_files(paths.quarantine)
    if not decisions:
        print("no .decision.json files found")
        return 0

    applied = 0
    skipped = 0

    for decision_file in decisions:
        try:
            payload = _load_payload(decision_file)
        except Exception as e:
            print(f"skip {decision_file.name}: invalid JSON ({e})")
            skipped += 1
            continue

        src, match_reason = _candidate_source_path(paths.quarantine, decision_file, payload)
        if not src or not src.exists():
            print(f"skip {decision_file.name}: source file not found ({match_reason})")
            skipped += 1
            continue

        decision = m.LLMDecision.from_dict(payload)
        routing = m.resolve_destination(paths, mapping_cfg, decision)
        if routing.forced_quarantine:
            print(f"skip {decision_file.name}: routing requires quarantine")
            skipped += 1
            continue

        auto_ok, reason = m.should_auto_apply(mapping_cfg, decision)
        if not auto_ok:
            print(f"skip {decision_file.name}: auto-apply gate '{reason}'")
            skipped += 1
            continue

        new_name = src.name if routing.rename_policy == "keep" else (decision.suggested_name or src.name)
        run_id = datetime.utcnow().strftime("%Y%m%d-%H%M%S")
        target_path = routing.dest_dir / new_name

        if dry_run:
            print(f"[DRY] {decision_file.name}: {src.name} -> {target_path}")
            applied += 1
            continue

        moved = m.move_with_ledger(
            paths,
            src,
            routing.dest_dir,
            new_name,
            paths.logs / "ledger.jsonl",
            run_id,
            m.sha256_file(src),
            "triage_apply",
            action="triage_apply",
        )
        try:
            decision_file.unlink()
        except Exception:
            pass
        print(f"applied: {src.name} -> {moved}")
        applied += 1

    print(f"triage-apply complete: {applied} applied, {skipped} skipped")
    return 0


def main() -> int:
    args = _parse_args()
    return apply_decisions(Path(args.root), args.dry_run)


if __name__ == "__main__":
    raise SystemExit(main())
